[package]
name = "citrus"
version = "0.1.0-prealpha"
edition = "2021"

description = "A Rusty scripting language designed to be used for simple utilities."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
